---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "b9iwrxRmiYM5/6DOvMPYQCclgwS3Q0rrMrG3Ee9THQLUklrRlhtEGqaGcoGUAaQ4btRpW6BGNGp8J2kcjGpudr/hhsw+p8mtuFsJf/vlc/xMlC+k5PPOlGUMDRkmcOwU+209dnBwpDMvoZmFQ3dwMfdLsiXSvLbUsCsMMD/1WjhGyRhbaRI68i91ojjmJ6yzw1EZUv67Ho3RHpnmRopyRU/j3nSZfsmtTBgSxchYZ2kRfxrKPbFv9zIuyAKFzytQQK3rDQ5n7D6R1SRPcECdcmRRMOM0xdsA+mkbnMPcVaUz0KFb0Y8H8BqpSCefAkH6ke6BCCChMnCJPk1Gkv7GuBNvLgm+3sXl5OMfjO9zeY9qZGPho79zX/XZLw0fT2RqNzAogRpWpTnTpC3vVcirFIVq+1dMJqBE1DVoup1UaLC6t8plCcpTNjkxbI5Fyf/mKHErs66hL1BQNyMvyxlTjs+fjvkhlC3x5H5++qOVB4JzJuWRWDra0tOThat4JMRzt2ilqdFZ33btRyPahus9b240nwPmZ7sC9AKXiw89fEFix+FqfexJeg8RE/thxv/dHw3k3OiXnkMSAF2XjJ4A+HEJrBL1Ev4VyZj2eL+JogXhu5Cf428jALThw2WnobMw1SSQzhRFtUq+FqksvGhg+8davzsmIalplh+CJSsIhzo="
  email: false
