---
- name: test if ca_passphrase is set correctly
  assert:
    that:
      - ca_passphrase is defined
      - ca_passphrase | length > 0

- name: test if ca_common_name is set correctly
  assert:
    that:
      - ca_common_name is defined
      - ca_common_name | length > 0

- name: test if ca_country_name is set correctly
  assert:
    that:
      - ca_country_name is defined
      - ca_country_name | length > 0
      - ca_country_name | length <= 2

- name: test if ca_email_address is set correctly
  assert:
    that:
      - ca_email_address is defined
      - ca_email_address | length > 0

- name: test if ca_organization_name is set correctly
  assert:
    that:
      - ca_organization_name is defined
      - ca_organization_name | length > 0

- name: test if ca_organizational_unit_name is set correctly
  assert:
    that:
      - ca_organizational_unit_name is defined
      - ca_organizational_unit_name | length > 0

- name: test if ca_state_or_province_name is set correctly
  assert:
    that:
      - ca_state_or_province_name is defined
      - ca_state_or_province_name | length > 0

- name: test if ca_requests is set correctly
  assert:
    that:
      - ca_requests | length > 0
      - ca_requests is iterable
  when:
    - ca_requests is defined

- name: test if item of ca_requests is set correctly
  assert:
    that:
      - item is defined
      - item | length > 0
    quiet: yes
  loop: "{{ ca_requests }}"
  when:
    - ca_requests is defined
    - item.name is not defined

- name: test if item of ca_requests with details is set correctly
  assert:
    that:
      - item.name | length > 0
    quiet: yes
  loop: "{{ ca_requests }}"
  loop_control:
    label: "{{ item.name | default('item.name is not set') }}"
  when:
    - ca_requests is defined
    - item.name is defined

- name: test if ca_publication_location is set correctly
  assert:
    that:
      - ca_publication_location is defined
      - ca_publication_location | length > 0

- name: test if ca_openssl_path is set correctly
  assert:
    that:
      - ca_openssl_path is defined
      - ca_openssl_path | length > 0
