---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    ca_requests:
      - name: my_ca.example.com
        passphrase: WoNtT3L1
        country_name: NL
        email_address: robert@meinit.nl
        organization_name: Some Corporation
        organizational_unit_name: Department X

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.httpd
    - role: ansible-role-ca
