---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  vars:
    httpd_ignore_docker: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.httpd
    - role: ansible-role-ca
