---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    ca_requests:
      - "{{ ansible_fqdn }}"
      - name: my_ca.example.com
        passphrase: WoNtT3L1
        cipher: aes256
        country_name: NL
        email_address: robert@meinit.nl
        organization_name: Some Corporation
        organizational_unit_name: Department X

  roles:
    - role: ansible-role-ca
